apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arthurmadureira
  name: project2-pv-arthurmadureira
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local